# Generated by Django 4.1.6 on 2023-02-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(blank=True, max_length=225, null=True)),
                ('phone', models.CharField(max_length=225)),
                ('note', models.TextField(blank=True, null=True)),
                ('total_price', models.IntegerField()),
                ('promo_code', models.CharField(blank=True, max_length=225, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
