# Generated by Django 4.1.5 on 2023-01-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='ordertranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
