# Generated by Django 4.1.5 on 2023-02-02 09:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='delivery_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=15),
        ),
        migrations.CreateModel(
            name='PaymentProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_providers/')),
                ('type', models.CharField(max_length=255)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
