# Generated by Django 4.1.5 on 2023-01-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shops.shopcategory'),
        ),
    ]
