# Generated by Django 4.1.5 on 2023-01-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='started_at',
            new_name='starts_at',
        ),
    ]
