# Generated by Django 4.1.5 on 2023-01-29 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_rename_started_at_shop_starts_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='long',
            new_name='lon',
        ),
    ]
