# Generated by Django 4.1.5 on 2023-01-25 20:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import shops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Shop Category',
                'verbose_name_plural': 'Shop Categories',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Shop Currency',
                'verbose_name_plural': 'Shop Currencies',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'РУССКИЙ'), ('en', 'ENGLISH')], max_length=50), size=None)),
                ('about_us', models.CharField(blank=True, max_length=1024, null=True)),
                ('delivery_price', models.IntegerField(blank=True, null=True, verbose_name='Delivery Price')),
                ('delivery_price_per_km', models.IntegerField(blank=True, null=True, verbose_name='Delivery Price Per KM')),
                ('minimum_delivery_price', models.IntegerField(blank=True, null=True)),
                ('free_delivery', models.BooleanField(blank=True, null=True)),
                ('about_us_image', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=100), default=shops.models.Shop.Defaults.delivery, size=None)),
                ('has_terminal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('lon', models.IntegerField(blank=True, null=True)),
                ('lat', models.IntegerField(blank=True, null=True)),
                ('delivery_terms', models.CharField(blank=True, max_length=2048, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.currency')),
            ],
        ),
    ]
