# Generated by Django 4.1.5 on 2023-01-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopcategory_shop_shop_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Shop Category', 'verbose_name_plural': 'Shop Categories'},
        ),
    ]
